## This manifest only exists for the signal module

[package]
name = "onlyforthe/dependencies"
version = "0.0.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@2.0.1"